package com.vitaltrace.app.feature.nurseportal.domain.model

data class NurseSummary(val nurse: NurseInfo, val assignedPatientsCount: Int, val alerts: NurseAlertsSummary, val appointments: List<NurseAppointment>)
data class NurseInfo(val id: Long, val fullName: String, val professionalCode: String, val specialty: String?)
data class NurseAlertsSummary(val pending: Int, val new: Int, val critical: Int)
data class NursePatient(val id: Long, val recordNumber: String, val fullName: String, val birthDate: String?, val age: Int?, val sex: String?, val status: String, val activeAlerts: Int, val criticalAlerts: Int, val lastMeasurement: NurseMeasurement?, val nextAppointment: NurseAppointment?)
data class NurseProfile(val id: Long, val fullName: String, val recordNumber: String, val sex: String?, val birthDate: String?, val age: Int?, val phone: String?, val emergencyName: String?, val emergencyPhone: String?, val status: String)
data class NurseAppointment(val id: Long, val patientId: Long, val scheduledAt: String, val durationMinutes: Int, val reason: String, val status: String, val professional: NurseProfessional?)
data class NurseProfessional(val id: Long, val fullName: String?, val type: String?, val specialty: String?)
data class NurseMeasurement(val id: Long, val patientId: Long, val typeId: Long?, val typeName: String?, val baseUnit: String?, val value: String, val unit: String, val measuredAt: String, val origin: String, val observation: String?, val reviewStatus: String?)
data class NurseMeasurementType(val id: Long, val name: String, val unit: String, val decimals: Int, val active: Boolean)
data class NurseDiagnosis(val id: Long, val cieCode: String?, val description: String, val date: String, val status: String)
data class NurseMedication(val id: Long?, val name: String?, val dose: String?, val route: String?, val frequency: String?, val schedules: String?)
data class NurseTreatment(val id: Long, val patientId: Long, val indications: String, val startDate: String, val endDate: String?, val status: String, val diagnosis: NurseDiagnosis?, val medications: List<NurseMedication>)
data class NurseEvolution(val id: Long, val summary: String, val status: String, val recordedAt: String)
data class NurseHistory(val patient: NursePatient, val diagnoses: List<NurseDiagnosis>, val evolutions: List<NurseEvolution>, val treatments: List<NurseTreatment>, val measurements: List<NurseMeasurement>)
data class NurseAlert(val id: Long, val patientId: Long, val measurementId: Long?, val type: String, val severity: String, val status: String, val description: String, val generatedAt: String, val closedAt: String?, val history: List<NurseAlertHistory>)
data class NurseAlertHistory(val id: Long, val action: String, val previousStatus: String?, val newStatus: String?, val comment: String?, val createdAt: String?)
data class NursePatientSummary(val patient: NursePatient, val recentMeasurements: List<NurseMeasurement>, val diagnoses: List<NurseDiagnosis>, val activeTreatments: List<NurseTreatment>, val upcomingAppointment: NurseAppointment?, val activeAlerts: List<NurseAlert>)